### ISSUE TITLE
Bad path to img

### ISSUE THREAD

**Issue by JuanCarlosFrutos** [RFrutos/conferencias#1]
https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/index.html#L84

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/index.html#L109

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/index.html#L122

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/index.html#L128

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/css/main.css#L229

**Comment by RFrutos** [comment]
Done
