### ISSUE TITLE
Indentation problem

### ISSUE THREAD

**Issue by JuanCarlosFrutos** [RFrutos/conferencias#3]
You should install some extensión to auto indent your code. 

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/css/main.css#L461

Incorrect number of intros and ';'

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/css/main.css#L344

**Comment by RFrutos** [comment]
Done
