### ISSUE TITLE
Horizontal scroll

### ISSUE THREAD

**Issue by JuanCarlosFrutos** [RFrutos/conferencias#6]
Use width with px is dangerous. Be careful!  Pixel width is generating unnecessary scroll.

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/css/main.css#L236

You should read about property [```box-sixing```](https://www.w3schools.com/cssreF/css3_pr_box-sizing.asp). Margin is generating unnecessary scroll because they are too big.

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/css/main.css#L238

Try to use SMALL percentages for margin and padding. If you need to put a big percentage probably will be better use some type of display. Margin is generating unnecessary scroll because they are too big.

https://github.com/RFrutos/conferencias/blob/797f6c317cb6d8125bc0066d120ddebfbb0187bb/PROYECTO/css/main.css#L146

Scroll appears again at size of 940px, this time is due to responsive problems (Nav var is too width). But keep in mind that you still have some big margin and paddings it will be a problem when start developing mobile version

**Comment by RFrutos** [comment]
Done
